### ISSUE TITLE
mbed-os-example-sockets not working on UBLOX_C027

### ISSUE THREAD

**Issue by haseeb-ublox** [ARMmbed/mbed-os-example-sockets#12]
Hi,

I have tried to build this example using mbed CLI through following command:
`mbed compile -t gcc_arm -m UBLOX_C027`

Binary is compiling successfully but it is not working on UBLOX_C027

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3667

**Comment by JanneKiiskila** [comment]
Did you modify the stacks, so that it actually uses the cellular stack? This app defaults to an ethernet stack by default.

Other alternative (which you need with UBLOX_ODIN) is the EMAC override, ethernet does not work by default with that UBLOX_ODIN at least. Look in [easy-connect](https://github.com/ARMmbed/easy-connect#specifying-the-connectivity-method) under `ETHERNET` part for the EMAC override magic.

@ARMmbed/team-ublox  - does the EMAC override have to exist also for C027?

**Comment by SeppoTakalo** [comment]
C027 does not have Ethernet support after Emac was merged in. Its based on LPC17* target. Fix PR in progress https://github.com/ARMmbed/mbed-os/pull/7086

**Comment by SeppoTakalo** [comment]
And the `"target.device_has_remove": ["EMAC"]` is obsoleted for Mbed OS 5.9.

Correct way is to use: https://github.com/ARMmbed/mbed-os-example-sockets/blob/mbed-os-5.9.0-oob/mbed_app.json#L7

**Comment by SeppoTakalo** [comment]
This will be fixed in Mbed OS 5.9.1
